
# Base Python image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy dependencies first
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copy backend code, models, and outputs
COPY app.py .
COPY models/ ./models
COPY outputs/ ./outputs

#Expose FastAPI port
EXPOSE 8000

#Start FastAPI using uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
